from nmigen import *
from nmigen_boards.tinyfpga_bx import *
from nmigen.build import Resource, Subsignal, Pins

class PaintController(TinyFPGABXPlatform):
    resources = TinyFPGABXPlatform.resources + [
        Resource("spi",
            0,
            Subsignal("clk", Pins("4", conn=("gpio", 0), dir="i")),
            Subsignal("ss", Pins("5", conn=("gpio", 0), dir="i")),
            Subsignal("miso", Pins("6", conn=("gpio", 0), dir="o")),
            Subsignal("mosi", Pins("7", conn=("gpio", 0), dir="i")),
        ),
        Resource("dispenser",
            0,
            Subsignal("stepper", Pins("8", conn=("gpio", 0), dir="o")),
            Subsignal("limit_top", Pins("9", conn=("gpio", 0), dir="i")),
            Subsignal("limit_bottom", Pins("10", conn=("gpio", 0), dir="i")),
        ),
        Resource("dispenser",
            1,
            Subsignal("stepper", Pins("11", conn=("gpio", 0), dir="o")),
            Subsignal("limit_top", Pins("12", conn=("gpio", 0), dir="i")),
            Subsignal("limit_bottom", Pins("13", conn=("gpio", 0), dir="i")),
        ),
        Resource("dispenser",
            2,
            Subsignal("stepper", Pins("14", conn=("gpio", 0), dir="o")),
            Subsignal("limit_top", Pins("15", conn=("gpio", 0), dir="i")),
            Subsignal("limit_bottom", Pins("16", conn=("gpio", 0), dir="i")),
        ),
        Resource("dispenser",
            3,
            Subsignal("stepper", Pins("17", conn=("gpio", 0), dir="o")),
            Subsignal("limit_top", Pins("18", conn=("gpio", 0), dir="i")),
            Subsignal("limit_bottom", Pins("19", conn=("gpio", 0), dir="i")),
        ),
        Resource("dispenser",
            4,
            Subsignal("stepper", Pins("20", conn=("gpio", 0), dir="o")),
            Subsignal("limit_top", Pins("21", conn=("gpio", 0), dir="i")),
            Subsignal("limit_bottom", Pins("22", conn=("gpio", 0), dir="i")),
        ),
        Resource("motor_enable",
            0,
            Pins("23", conn=("gpio", 0), dir="o"),
        )
    ]
